# ant test -Dtests.filter=*failures* -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655

junit-parallel:
   [junit4] <JUnit4> says hello. Random seed: deadbeef
   [junit4] Expected execution time on slave 0:     0.00s
   [junit4] Expected execution time on slave 1:     0.00s
   [junit4] Expected execution time on slave 2:     0.00s
   [junit4] Expected execution time on slave 3:     0.00s
   [junit4] Executing 9 suites with 4 JVMs.
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn02BeforeClass
   [junit4] ERROR   0.00s S1 | TestFailOn02BeforeClass (suite)
   [junit4]    > Throwable #1: java.lang.RuntimeException: Exception on @BeforeClass.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn02BeforeClass.beforeClass(TestFailOn02BeforeClass.java:13)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    > 	at java.lang.reflect.Method.invoke(Method.java:601)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    >
   [junit4] Tests run:   0, Failures:   0, Errors:   1, Skipped:   0, Time:  0.24s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn07After
   [junit4] ERROR   0.10s S3 | TestFailOn07After.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Failure on @After.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn07After.after(TestFailOn07After.java:13)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    > 	at java.lang.reflect.Method.invoke(Method.java:601)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:36)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$SubclassSetupTeardownRule$1.evaluate(LuceneTestCase.java:700)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$InternalSetupTeardownRule$1.evaluate(LuceneTestCase.java:599)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$TestResultInterceptorRule$1.evaluate(LuceneTestCase.java:504)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$RememberThreadRule$1.evaluate(LuceneTestCase.java:562)
   [junit4]    > 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
   [junit4]    > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > 
   [junit4]   2> NOTE: reproduce with: ant test -Dtestcase=TestFailOn07After -Dtestmethod=testMethod -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655 -Dargs="-Dfile.encoding=Cp1252"
   [junit4]   2>
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.28s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn08AfterClass
   [junit4] ERROR   0.00s S0 | TestFailOn08AfterClass (suite)
   [junit4]    > Throwable #1: java.lang.RuntimeException: Failure on @AfterClass.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn08AfterClass.afterClass(TestFailOn08AfterClass.java:13)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    > 	at java.lang.reflect.Method.invoke(Method.java:601)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:36)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    >
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.33s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn06Test
   [junit4] ERROR   0.06s S2 | TestFailOn06Test.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Exception on @Test method.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn06Test.testMethod(TestFailOn06Test.java:12)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    > 	at java.lang.reflect.Method.invoke(Method.java:601)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
   [junit4]    > 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$SubclassSetupTeardownRule$1.evaluate(LuceneTestCase.java:700)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$InternalSetupTeardownRule$1.evaluate(LuceneTestCase.java:599)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$TestResultInterceptorRule$1.evaluate(LuceneTestCase.java:504)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$RememberThreadRule$1.evaluate(LuceneTestCase.java:562)
   [junit4]    > 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
   [junit4]    > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > 
   [junit4]   2> NOTE: reproduce with: ant test -Dtestcase=TestFailOn06Test -Dtestmethod=testMethod -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655 -Dargs="-Dfile.encoding=Cp1252"
   [junit4]   2>
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.35s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn01ClassLoad
   [junit4] ERROR   0.00s S0 | TestFailOn01ClassLoad (suite)
   [junit4]    > Throwable #1: java.lang.ExceptionInInitializerError
   [junit4]    > 	at java.lang.Class.forName0(Native Method)
   [junit4]    > 	at java.lang.Class.forName(Class.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.instantiate(SlaveMain.java:138)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:116)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > Caused by: java.lang.ArithmeticException: / by zero
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn01ClassLoad.<clinit>(TestFailOn01ClassLoad.java:11)
   [junit4]    > 	... 6 more
   [junit4]    >
   [junit4] Tests run:   0, Failures:   0, Errors:   1, Skipped:   0, Time:  0.00s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn05RuleAfter
   [junit4] ERROR   0.01s S2 | TestFailOn05RuleAfter.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Failure on @Rule (after test).
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn05RuleAfter$1$1.evaluate(TestFailOn05RuleAfter.java:20)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$SubclassSetupTeardownRule$1.evaluate(LuceneTestCase.java:700)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$InternalSetupTeardownRule$1.evaluate(LuceneTestCase.java:599)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$TestResultInterceptorRule$1.evaluate(LuceneTestCase.java:504)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$RememberThreadRule$1.evaluate(LuceneTestCase.java:562)
   [junit4]    > 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
   [junit4]    > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > 
   [junit4]   2> NOTE: reproduce with: ant test -Dtestcase=TestFailOn05RuleAfter -Dtestmethod=testMethod -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655 -Dargs="-Dfile.encoding=Cp1252"
   [junit4]   2>
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.01s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn03NewInstance
   [junit4] ERROR   0.00s S3 | TestFailOn03NewInstance.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Exception on new instance.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn03NewInstance.<init>(TestFailOn03NewInstance.java:12)
   [junit4]    > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   [junit4]    > 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   [junit4]    > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:187)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:236)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:233)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    >
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.01s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn05RuleBefore
   [junit4] ERROR   0.01s S1 | TestFailOn05RuleBefore.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Failure on @Rule (before test).
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn05RuleBefore$1$1.evaluate(TestFailOn05RuleBefore.java:19)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$SubclassSetupTeardownRule$1.evaluate(LuceneTestCase.java:700)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$InternalSetupTeardownRule$1.evaluate(LuceneTestCase.java:599)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$TestResultInterceptorRule$1.evaluate(LuceneTestCase.java:504)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$RememberThreadRule$1.evaluate(LuceneTestCase.java:562)
   [junit4]    > 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
   [junit4]    > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > 
   [junit4]   2> NOTE: reproduce with: ant test -Dtestcase=TestFailOn05RuleBefore -Dtestmethod=testMethod -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655 -Dargs="-Dfile.encoding=Cp1252"
   [junit4]   2>
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.02s <<< FAILURES!
   [junit4]  
   [junit4] Running org.apache.lucene.util.junitcompat.failures.TestFailOn04Before
   [junit4] ERROR   0.01s S2 | TestFailOn04Before.testMethod
   [junit4]    > Throwable #1: java.lang.RuntimeException: Exception on new instance.
   [junit4]    > 	at org.apache.lucene.util.junitcompat.failures.TestFailOn04Before.before(TestFailOn04Before.java:14)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [junit4]    > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [junit4]    > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [junit4]    > 	at java.lang.reflect.Method.invoke(Method.java:601)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
   [junit4]    > 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
   [junit4]    > 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$SubclassSetupTeardownRule$1.evaluate(LuceneTestCase.java:700)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$InternalSetupTeardownRule$1.evaluate(LuceneTestCase.java:599)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$TestResultInterceptorRule$1.evaluate(LuceneTestCase.java:504)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCase$RememberThreadRule$1.evaluate(LuceneTestCase.java:562)
   [junit4]    > 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
   [junit4]    > 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
   [junit4]    > 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:165)
   [junit4]    > 	at org.apache.lucene.util.LuceneTestCaseRunner.runChild(LuceneTestCaseRunner.java:57)
   [junit4]    > 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
   [junit4]    > 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
   [junit4]    > 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
   [junit4]    > 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
   [junit4]    > 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
   [junit4]    > 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
   [junit4]    > 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
   [junit4]    > 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
   [junit4]    > 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.execute(SlaveMain.java:124)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMain.main(SlaveMain.java:186)
   [junit4]    > 	at com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe.main(SlaveMainSafe.java:12)
   [junit4]    > 
   [junit4]   2> NOTE: reproduce with: ant test -Dtestcase=TestFailOn04Before -Dtestmethod=testMethod -Dtests.seed=-737472ec6455983d:77a4c0da1ce834dd:1a2ea2ed4eba1655 -Dargs="-Dfile.encoding=Cp1252"
   [junit4]   2>
   [junit4] Tests run:   1, Failures:   0, Errors:   1, Skipped:   0, Time:  0.01s <<< FAILURES!
   [junit4]  
   [junit4] Slave 0:     0.46 ..     1.12 =     0.66s
   [junit4] Slave 1:     0.49 ..     1.14 =     0.64s
   [junit4] Slave 2:     0.48 ..     1.16 =     0.69s
   [junit4] Slave 3:     0.47 ..     1.15 =     0.68s
   [junit4] Execution time total: 1.17 sec.
   [junit4] Tests summary: 9 suites, 7 tests, 3 suite-level errors, 6 errors

BUILD FAILED
